In [7]:
from sklearn.datasets import load_wine
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
import numpy as np

In [9]:
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer
from sklearn.neighbors import LocalOutlierFactor

# Load the wine dataset
wine_data = load_wine()
X = wine_data.data  # Features
y = wine_data.target  # Target variable

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale the data using MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Missing value imputation
imputer = SimpleImputer(strategy='mean')  # You can choose a suitable imputation strategy
X_train_scaled_imputed = imputer.fit_transform(X_train_scaled)
X_test_scaled_imputed = imputer.transform(X_test_scaled)

# Outlier removal
outlier_detector = LocalOutlierFactor()
outlier_labels_train = outlier_detector.fit_predict(X_train_scaled_imputed)
outlier_labels_test = outlier_detector.fit_predict(X_test_scaled_imputed)
X_train_scaled_imputed_no_outliers = X_train_scaled_imputed[outlier_labels_train == 1]
y_train_no_outliers = y_train[outlier_labels_train == 1]
X_test_scaled_imputed_no_outliers = X_test_scaled_imputed[outlier_labels_test == 1]
y_test_no_outliers = y_test[outlier_labels_test == 1]


In [10]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Create a K-nearest neighbors (KNN) classifier
knn = KNeighborsClassifier(n_neighbors=3)

# Fit the classifier to the training data
knn.fit(X_train_scaled_imputed_no_outliers, y_train_no_outliers)

# Predict the cultivator for the test data
y_pred = knn.predict(X_test_scaled_imputed_no_outliers)

# Evaluate the accuracy of the prediction
accuracy = accuracy_score(y_test_no_outliers, y_pred)

# Print the predicted cultivator for each wine
print("Predicted cultivator for each wine:")
for wine, prediction in zip(X_test_scaled_imputed_no_outliers, y_pred):
    print(f"Features: {wine}  Predicted Cultivator: {prediction}")


Predicted cultivator for each wine:
Features: [0.68684211 0.45010183 0.64171123 0.2371134  0.5        0.59310345
 0.56751055 0.0754717  0.39240506 0.29840142 0.3902439  0.76556777
 0.44680851]  Predicted Cultivator: 0
Features: [0.83684211 0.64154786 0.57754011 0.42783505 0.44565217 0.64482759
 0.48734177 0.32075472 0.26265823 0.31083481 0.31707317 0.75457875
 0.6319937 ]  Predicted Cultivator: 0
Features: [0.5        0.3910387  0.71657754 0.53608247 0.2826087  0.19310345
 0.03375527 0.75471698 0.10443038 0.25399645 0.23577236 0.38095238
 0.2537431 ]  Predicted Cultivator: 2
Features: [0.71052632 0.12423625 0.71657754 0.61340206 0.33695652 0.69655172
 0.61392405 0.30188679 0.62025316 0.35168739 0.57723577 0.52747253
 0.79353822]  Predicted Cultivator: 0
Features: [0.35263158 0.05702648 0.29946524 0.46391753 0.08695652 0.38965517
 0.35021097 0.26415094 0.19620253 0.26110124 0.5203252  0.80952381
 0.18282112]  Predicted Cultivator: 1
Features: [0.86052632 0.20977597 0.72727273 0.48453608

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


In [25]:
from sklearn.datasets import load_wine
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

# Load the dataset
wine_data = load_wine()
X = wine_data.data
y = wine_data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the classifier
clf = DecisionTreeClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Predict the cultivator for the test set
predictions = clf.predict(X_test)
# Print the predicted cultivator for each wine
print("Predicted cultivator for each wine:")
for wine, prediction in zip(X_test_scaled_imputed_no_outliers, y_pred):
    print(f"Features: {wine}  Predicted Cultivator: {prediction}")

Predicted cultivator for each wine:
Features: [0.68684211 0.45010183 0.64171123 0.2371134  0.5        0.59310345
 0.56751055 0.0754717  0.39240506 0.29840142 0.3902439  0.76556777
 0.44680851]  Predicted Cultivator: 0
Features: [0.83684211 0.64154786 0.57754011 0.42783505 0.44565217 0.64482759
 0.48734177 0.32075472 0.26265823 0.31083481 0.31707317 0.75457875
 0.6319937 ]  Predicted Cultivator: 0
Features: [0.5        0.3910387  0.71657754 0.53608247 0.2826087  0.19310345
 0.03375527 0.75471698 0.10443038 0.25399645 0.23577236 0.38095238
 0.2537431 ]  Predicted Cultivator: 2
Features: [0.71052632 0.12423625 0.71657754 0.61340206 0.33695652 0.69655172
 0.61392405 0.30188679 0.62025316 0.35168739 0.57723577 0.52747253
 0.79353822]  Predicted Cultivator: 0
Features: [0.35263158 0.05702648 0.29946524 0.46391753 0.08695652 0.38965517
 0.35021097 0.26415094 0.19620253 0.26110124 0.5203252  0.80952381
 0.18282112]  Predicted Cultivator: 1
Features: [0.86052632 0.20977597 0.72727273 0.48453608

In [26]:
from sklearn.datasets import load_wine
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

# Load the dataset
wine_data = load_wine()
X = wine_data.data
y = wine_data.target

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Create the classifier
clf = RandomForestClassifier()

# Train the classifier
clf.fit(X_train, y_train)

# Predict the cultivator for the test set
predictions = clf.predict(X_test)
# Print the predicted cultivator for each wine
print("Predicted cultivator for each wine:")
for wine, prediction in zip(X_test_scaled_imputed_no_outliers, y_pred):
    print(f"Features: {wine}  Predicted Cultivator: {prediction}")

Predicted cultivator for each wine:
Features: [0.68684211 0.45010183 0.64171123 0.2371134  0.5        0.59310345
 0.56751055 0.0754717  0.39240506 0.29840142 0.3902439  0.76556777
 0.44680851]  Predicted Cultivator: 0
Features: [0.83684211 0.64154786 0.57754011 0.42783505 0.44565217 0.64482759
 0.48734177 0.32075472 0.26265823 0.31083481 0.31707317 0.75457875
 0.6319937 ]  Predicted Cultivator: 0
Features: [0.5        0.3910387  0.71657754 0.53608247 0.2826087  0.19310345
 0.03375527 0.75471698 0.10443038 0.25399645 0.23577236 0.38095238
 0.2537431 ]  Predicted Cultivator: 2
Features: [0.71052632 0.12423625 0.71657754 0.61340206 0.33695652 0.69655172
 0.61392405 0.30188679 0.62025316 0.35168739 0.57723577 0.52747253
 0.79353822]  Predicted Cultivator: 0
Features: [0.35263158 0.05702648 0.29946524 0.46391753 0.08695652 0.38965517
 0.35021097 0.26415094 0.19620253 0.26110124 0.5203252  0.80952381
 0.18282112]  Predicted Cultivator: 1
Features: [0.86052632 0.20977597 0.72727273 0.48453608

In [13]:
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest classifier
rf = RandomForestClassifier(random_state=42)

# Fit the classifier to the training data
rf.fit(X_train_scaled_imputed_no_outliers, y_train_no_outliers)

# Get feature importances
importances_rf = rf.feature_importances_

# Sort the features by importance in descending order
sorted_indices_rf = np.argsort(importances_rf)[::-1]

# Get the top 3 predictive features
top_features_rf = sorted_indices_rf[:3]
print(top_features_rf)

[ 6  9 12]


In [18]:
from sklearn.feature_selection import SelectFromModel
from sklearn.ensemble import RandomForestClassifier

# Create a Random Forest classifier
rf = RandomForestClassifier(random_state=42)

# Perform feature selection using SelectFromModel with Random Forest
selector = SelectFromModel(estimator=rf)
selector.fit(X_train_scaled_imputed_no_outliers, y_train_no_outliers)

# Get the mask of selected features
feature_mask_selectfrommodel = selector.get_support()

# Get the top 3 predictive features
top_features_selectfrommodel = np.argsort(feature_mask_selectfrommodel)[-3:]
print(top_features_selectfrommodel)


[10 11 12]


In [16]:
from sklearn.feature_selection import SelectKBest, mutual_info_classif

# Perform feature selection using SelectKBest with Mutual Information
selector = SelectKBest(score_func=mutual_info_classif, k=3)
selector.fit(X_train_scaled_imputed_no_outliers, y_train_no_outliers)

# Get the mask of selected features
feature_mask_selectkbest = selector.get_support()

# Get the top 3 predictive features
top_features_selectkbest = np.argsort(feature_mask_selectkbest)[-3:]
print(top_features_selectkbest)

[ 6  9 12]


In [21]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Fit the classifier to the training data and make predictions
knn.fit(X_train_scaled_imputed_no_outliers, y_train_no_outliers)
y_pred = knn.predict(X_test_scaled_imputed_no_outliers)

# Calculate the accuracy score
accuracy = accuracy_score(y_test_no_outliers, y_pred)

# Print accuracy score
print("Accuracy:", accuracy)
# Print confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test_no_outliers, y_pred))


Accuracy: 0.9444444444444444

Confusion Matrix:
[[14  0  0]
 [ 1 12  1]
 [ 0  0  8]]


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)
